version: '3.8'

services:
  web:
    build: .
    command: sh -c "python manage.py migrate && python manage.py configurar_roles --email admin@codeacademy.com --password admin123 && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=codeacademy
      - POSTGRES_USER=codeacademy
      - POSTGRES_PASSWORD=codeacademy
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=codeacademy
      - POSTGRES_PASSWORD=codeacademy
      - POSTGRES_DB=codeacademy
    ports:
      - "5432:5432"

volumes:
  postgres_data:
